---
name: noip-renewer
version: 2025.10.4
slug: noip-renewer
description: simao-silva/noip-renewer for homeassistant addon
url: "https://github.com/habuild/hassio/tree/main/noip-renewer"
stage: experimental
init: false
image: "ghcr.io/habuild/{arch}-addon-noip-renewer"
hassio_api: true
homeassistant_api: true
arch:
  - aarch64
panel_icon: mdi:certificate
map:
  - share:rw
options:
  NOIP_Email: "!secret NOIP_Email"
  NOIP_Password: "!secret NOIP_Password"
  NOIP_TOTP_KEY: "!secret NOIP_TOTP_KEY"
  Translate_Enabled: "false"
schema:
  NOIP_Email: "str?"
  NOIP_Password: "str?"
  NOIP_TOTP_KEY: "str?"
  Translate_Enabled: "str?"
